import PptxGenJS from 'pptxgenjs';
import {
  OSFDocument,
  MetaBlock,
  DocBlock,
  SlideBlock,
  SheetBlock,
  ChartBlock,
  DiagramBlock,
  OSFCodeBlock,
  type ChartDataSeries,
  type ContentBlock,
  type TextRun as OSFTextRun,
} from 'omniscript-parser';
import { Converter, ConverterOptions, ConversionResult } from './types';

type ThemeConfig = {
  primary: string;
  secondary: string;
  accent: string;
  text: string;
  background: string;
  border: string;
  tableBackground: string;
  titleFont: string;
  bodyFont: string;
};

type SlideBlockExtras = SlideBlock & {
  transition?: string;
  notes?: string;
};

type TransitionEffect = {
  type: string;
  dir?: string;
};

export class PPTXConverter implements Converter {
  getSupportedFormats(): string[] {
    return ['pptx'];
  }

  async convert(document: OSFDocument, options: ConverterOptions = {}): Promise<ConversionResult> {
    const pptx = new PptxGenJS();

    // Set presentation metadata
    this.setPresentationMetadata(pptx, document);

    // Configure theme and layout
    this.configureTheme(pptx, options.theme || 'default');

    // Process document blocks
    await this.generateSlides(pptx, document, options);

    const blob = await pptx.write();
    const arrayBuffer = await (blob as Blob).arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);

    return {
      buffer,
      mimeType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
      extension: 'pptx',
    };
  }

  private setPresentationMetadata(pptx: PptxGenJS, document: OSFDocument): void {
    const meta = this.getMetadata(document);

    pptx.author = String(meta.author) || 'OmniScript OSF';
    pptx.company = 'Generated by OmniScript';
    pptx.title = String(meta.title) || 'OSF Presentation';
    pptx.subject = 'Generated from OSF document';
  }

  private configureTheme(pptx: PptxGenJS, theme: string): void {
    const themeConfig = this.getThemeConfiguration(theme);

    pptx.defineLayout({
      name: 'OSF_LAYOUT',
      width: 10,
      height: 7.5,
    });

    pptx.theme = {
      headFontFace: themeConfig.titleFont,
      bodyFontFace: themeConfig.bodyFont,
    };

    // Note: Master slides removed for compatibility with pptxgenjs v4
  }

  private async generateSlides(
    pptx: PptxGenJS,
    document: OSFDocument,
    options: ConverterOptions
  ): Promise<void> {
    let hasCreatedTitleSlide = false;

    for (const block of document.blocks) {
      switch (block.type) {
        case 'meta':
          if (!hasCreatedTitleSlide && options.includeMetadata !== false) {
            this.createTitleSlide(pptx, block as MetaBlock, options);
            hasCreatedTitleSlide = true;
          }
          break;
        case 'doc':
          this.createDocSlides(pptx, block as DocBlock, options);
          break;
        case 'slide':
          this.createSlideFromBlock(pptx, block as SlideBlock, options);
          break;
        case 'sheet':
          this.createSheetSlide(pptx, block as SheetBlock, options);
          break;
        case 'chart':
          this.createChartSlide(pptx, block as ChartBlock, options);
          break;
        case 'diagram':
          this.createDiagramSlide(pptx, block as DiagramBlock, options);
          break;
        case 'osfcode':
          this.createCodeSlide(pptx, block as OSFCodeBlock, options);
          break;
      }
    }
  }

  private createTitleSlide(pptx: PptxGenJS, meta: MetaBlock, options: ConverterOptions): void {
    const slide = pptx.addSlide();
    const theme = this.getThemeConfiguration(options.theme || 'default');

    if (meta.props.title) {
      slide.addText(String(meta.props.title), {
        x: 1,
        y: 2,
        w: 8,
        h: 1.5,
        align: 'center',
        fontSize: 44,
        bold: true,
        color: theme.primary,
        fontFace: theme.titleFont,
      });
    }

    const subtitle: string[] = [];
    if (meta.props.author) subtitle.push(`By: ${String(meta.props.author)}`);
    if (meta.props.date) subtitle.push(String(meta.props.date));

    if (subtitle.length > 0) {
      slide.addText(subtitle.join(' | '), {
        x: 1,
        y: 4,
        w: 8,
        h: 0.8,
        align: 'center',
        fontSize: 20,
        color: theme.secondary,
        fontFace: theme.bodyFont,
      });
    }
  }

  private createDocSlides(pptx: PptxGenJS, doc: DocBlock, options: ConverterOptions): void {
    const content = doc.content || '';
    const theme = this.getThemeConfiguration(options.theme || 'default');

    // Split content into logical slides based on headings
    const sections = this.splitContentIntoSections(content);

    for (const section of sections) {
      const slide = pptx.addSlide();

      if (section.title) {
        slide.addText(section.title, {
          x: 0.5,
          y: 0.5,
          w: 9,
          h: 1,
          fontSize: 32,
          bold: true,
          color: theme.primary,
          fontFace: theme.titleFont,
        });
      }

      if (section.content.length > 0) {
        const contentText = this.formatContentForSlide(section.content);
        slide.addText(contentText, {
          x: 0.5,
          y: section.title ? 1.8 : 0.5,
          w: 9,
          h: section.title ? 4.7 : 6.2,
          fontSize: 18,
          color: theme.text,
          fontFace: theme.bodyFont,
          valign: 'top',
        });
      }
    }
  }

  private createSlideFromBlock(
    pptx: PptxGenJS,
    slideBlock: SlideBlock,
    options: ConverterOptions
  ): void {
    const slide = pptx.addSlide();
    const theme = this.getThemeConfiguration(options.theme || 'default');
    const slideExtras = slideBlock as SlideBlockExtras;

    // Apply layout based on slide props
    const layout = slideExtras.layout || 'TitleAndContent';

    // Add transition if specified
    if (slideExtras.transition) {
      const transition = this.getTransitionEffect(slideExtras.transition);
      if (transition) {
        (slide as unknown as { transition?: TransitionEffect }).transition = transition;
      }
    }

    // Add notes if specified
    if (slideExtras.notes) {
      slide.addNotes(String(slideExtras.notes));
    }

    // Render based on layout type
    switch (layout) {
      case 'TitleOnly':
        this.renderTitleOnlyLayout(slide, slideBlock, theme);
        break;
      case 'TitleAndContent':
      case 'TitleAndBullets':
        this.renderTitleAndContentLayout(slide, slideBlock, theme);
        break;
      case 'TwoColumn':
        this.renderTwoColumnLayout(slide, slideBlock, theme);
        break;
      case 'Blank':
        this.renderBlankLayout(slide, slideBlock, theme);
        break;
      default:
        this.renderTitleAndContentLayout(slide, slideBlock, theme);
    }
  }

  private renderTitleOnlyLayout(
    slide: PptxGenJS.Slide,
    slideBlock: SlideBlock,
    theme: ThemeConfig
  ): void {
    if (slideBlock.title) {
      slide.addText(slideBlock.title, {
        x: 0.5,
        y: 3,
        w: 9,
        h: 1.5,
        align: 'center',
        fontSize: 44,
        bold: true,
        color: theme.primary,
        fontFace: theme.titleFont,
      });
    }
  }

  private renderTitleAndContentLayout(
    slide: PptxGenJS.Slide,
    slideBlock: SlideBlock,
    theme: ThemeConfig
  ): void {
    // Add slide title
    if (slideBlock.title) {
      slide.addText(slideBlock.title, {
        x: 0.5,
        y: 0.5,
        w: 9,
        h: 1,
        fontSize: 32,
        bold: true,
        color: theme.primary,
        fontFace: theme.titleFont,
      });
    }

    // Add slide content
    if (slideBlock.content) {
      let yPosition = slideBlock.title ? 1.8 : 0.5;

      for (const contentBlock of slideBlock.content) {
        if (contentBlock.type === 'unordered_list') {
          const bullets = contentBlock.items.map(item => {
            const itemText = item.content.map(this.extractText).join('');
            return this.parseInlineFormatting(itemText);
          });

          for (const bullet of bullets) {
            slide.addText(bullet, {
              x: 0.5,
              y: yPosition,
              w: 9,
              h: 0.6,
              fontSize: 20,
              color: theme.text,
              fontFace: theme.bodyFont,
              bullet: { type: 'bullet' },
            });
            yPosition += 0.6;
          }
        } else if (contentBlock.type === 'paragraph') {
          const paragraphText = contentBlock.content.map(this.extractText).join('');
          const formattedText = this.parseInlineFormatting(paragraphText);

          slide.addText(formattedText, {
            x: 0.5,
            y: yPosition,
            w: 9,
            h: 1.5,
            fontSize: 18,
            color: theme.text,
            fontFace: theme.bodyFont,
            valign: 'top',
          });

          yPosition += 1.8;
        }
      }
    }
  }

  private renderTwoColumnLayout(
    slide: PptxGenJS.Slide,
    slideBlock: SlideBlock,
    theme: ThemeConfig
  ): void {
    // Add slide title
    if (slideBlock.title) {
      slide.addText(slideBlock.title, {
        x: 0.5,
        y: 0.5,
        w: 9,
        h: 1,
        fontSize: 32,
        bold: true,
        color: theme.primary,
        fontFace: theme.titleFont,
      });
    }

    if (slideBlock.content && slideBlock.content.length > 0) {
      const halfContent = Math.ceil(slideBlock.content.length / 2);
      const leftColumn = slideBlock.content.slice(0, halfContent);
      const rightColumn = slideBlock.content.slice(halfContent);

      const yPosition = slideBlock.title ? 1.8 : 0.5;

      // Left column
      this.renderColumnContent(slide, leftColumn, 0.5, yPosition, 4.2, theme);

      // Right column
      this.renderColumnContent(slide, rightColumn, 5.3, yPosition, 4.2, theme);
    }
  }

  private renderBlankLayout(
    slide: PptxGenJS.Slide,
    slideBlock: SlideBlock,
    theme: ThemeConfig
  ): void {
    if (slideBlock.content) {
      let yPosition = 0.5;

      for (const contentBlock of slideBlock.content) {
        if (contentBlock.type === 'unordered_list') {
          const bullets = contentBlock.items.map(item => {
            const itemText = item.content.map(this.extractText).join('');
            return this.parseInlineFormatting(itemText);
          });

          for (const bullet of bullets) {
            slide.addText(bullet, {
              x: 0.5,
              y: yPosition,
              w: 9,
              h: 0.5,
              fontSize: 18,
              color: theme.text,
              fontFace: theme.bodyFont,
              bullet: { type: 'bullet' },
            });
            yPosition += 0.5;
          }
        } else if (contentBlock.type === 'paragraph') {
          const paragraphText = contentBlock.content.map(this.extractText).join('');
          const formattedText = this.parseInlineFormatting(paragraphText);

          slide.addText(formattedText, {
            x: 0.5,
            y: yPosition,
            w: 9,
            h: 1.2,
            fontSize: 16,
            color: theme.text,
            fontFace: theme.bodyFont,
          });

          yPosition += 1.4;
        }
      }
    }
  }

  private renderColumnContent(
    slide: PptxGenJS.Slide,
    content: ContentBlock[],
    x: number,
    y: number,
    width: number,
    theme: ThemeConfig
  ): void {
    let yPosition = y;

    for (const contentBlock of content) {
      if (contentBlock.type === 'unordered_list') {
        const bullets = contentBlock.items.map(item => {
          const itemText = item.content.map(this.extractText).join('');
          return this.parseInlineFormatting(itemText);
        });

        for (const bullet of bullets) {
          slide.addText(bullet, {
            x,
            y: yPosition,
            w: width,
            h: 0.5,
            fontSize: 16,
            color: theme.text,
            fontFace: theme.bodyFont,
            bullet: { type: 'bullet' },
          });
          yPosition += 0.5;
        }
      } else if (contentBlock.type === 'paragraph') {
        const paragraphText = contentBlock.content.map(this.extractText).join('');
        const formattedText = this.parseInlineFormatting(paragraphText);

        slide.addText(formattedText, {
          x,
          y: yPosition,
          w: width,
          h: 1,
          fontSize: 14,
          color: theme.text,
          fontFace: theme.bodyFont,
        });

        yPosition += 1.2;
      }
    }
  }

  private parseInlineFormatting(text: string): PptxGenJS.TextProps[] {
    const parts: PptxGenJS.TextProps[] = [];
    let currentIndex = 0;

    // Match **bold**, *italic*, `code`
    const boldRegex = /\*\*(.+?)\*\*/g;
    const italicRegex = /\*(.+?)\*/g;
    const codeRegex = /`(.+?)`/g;

    const matches: Array<{
      index: number;
      length: number;
      text: string;
      format: PptxGenJS.TextPropsOptions;
    }> = [];

    // Find all bold matches
    let match;
    while ((match = boldRegex.exec(text)) !== null) {
      matches.push({
        index: match.index,
        length: match[0].length,
        text: match[1],
        format: { bold: true },
      });
    }

    // Find all italic matches (excluding bold)
    const textWithoutBold = text.replace(/\*\*(.+?)\*\*/g, '  ');
    while ((match = italicRegex.exec(textWithoutBold)) !== null) {
      matches.push({
        index: match.index,
        length: match[0].length,
        text: match[1],
        format: { italic: true },
      });
    }

    // Find all code matches
    while ((match = codeRegex.exec(text)) !== null) {
      matches.push({
        index: match.index,
        length: match[0].length,
        text: match[1],
        format: { fontFace: 'Courier New', color: '666666' },
      });
    }

    // Sort matches by index
    matches.sort((a, b) => a.index - b.index);

    // Build text parts
    for (const m of matches) {
      if (m.index > currentIndex) {
        const plainText = text.substring(currentIndex, m.index);
        if (plainText) {
          parts.push({ text: plainText, options: {} });
        }
      }

      parts.push({ text: m.text, options: m.format });
      currentIndex = m.index + m.length;
    }

    // Add remaining text
    if (currentIndex < text.length) {
      const remainingText = text.substring(currentIndex);
      if (remainingText) {
        parts.push({ text: remainingText, options: {} });
      }
    }

    // If no formatting found, return the entire text
    if (parts.length === 0) {
      parts.push({ text, options: {} });
    }

    return parts;
  }

  private getTransitionEffect(transition: string): TransitionEffect | undefined {
    const transitions: Record<string, TransitionEffect> = {
      FadeIn: { type: 'fade' },
      Fade: { type: 'fade' },
      Slide: { type: 'push', dir: 'right' },
      Push: { type: 'push', dir: 'down' },
      Wipe: { type: 'wipe', dir: 'right' },
      Zoom: { type: 'zoom' },
      Split: { type: 'split', dir: 'vert' },
      Reveal: { type: 'reveal', dir: 'right' },
    };

    return transitions[transition] || transitions.Fade;
  }

  private createSheetSlide(pptx: PptxGenJS, sheet: SheetBlock, options: ConverterOptions): void {
    const slide = pptx.addSlide();
    const theme = this.getThemeConfiguration(options.theme || 'default');

    // Add sheet title
    if (sheet.name) {
      slide.addText(sheet.name, {
        x: 0.5,
        y: 0.5,
        w: 9,
        h: 1,
        fontSize: 28,
        bold: true,
        color: theme.primary,
        fontFace: theme.titleFont,
      });
    }

    if (sheet.data) {
      // Prepare table data
      const tableData = this.prepareTableData(sheet);

      if (tableData.length > 0) {
        slide.addTable(tableData, {
          x: 0.5,
          y: sheet.name ? 1.8 : 0.5,
          w: 9,
          h: sheet.name ? 4.7 : 6.2,
          fontSize: 14,
          color: theme.text,
          fontFace: theme.bodyFont,
          border: { pt: 1, color: theme.border },
          fill: { color: theme.tableBackground },
        });
      }
    }
  }

  private prepareTableData(sheet: SheetBlock): PptxGenJS.TableRow[] {
    const tableData: PptxGenJS.TableRow[] = [];

    // Add header row if columns are defined
    if (sheet.cols) {
      const cols = Array.isArray(sheet.cols)
        ? sheet.cols
        : String(sheet.cols)
            .replace(/[[\]]/g, '')
            .split(',')
            .map(s => s.trim());

      const headerRow: PptxGenJS.TableRow = cols.map(col => ({
        text: col,
        options: { bold: true, fill: { color: 'E8E8E8' } },
      }));

      tableData.push(headerRow);
    }

    if (sheet.data) {
      // Calculate table dimensions
      const coords = Object.keys(sheet.data).map(k => k.split(',').map(Number));
      const maxRow = Math.max(...coords.map(c => c[0]));
      const maxCol = Math.max(...coords.map(c => c[1]));

      // Add data rows
      for (let r = 1; r <= maxRow; r++) {
        const row: PptxGenJS.TableRow = [];
        for (let c = 1; c <= maxCol; c++) {
          const key = `${r},${c}`;
          const value = sheet.data[key] || '';
          row.push({ text: String(value) });
        }
        tableData.push(row);
      }
    }

    return tableData;
  }

  private splitContentIntoSections(content: string): Array<{ title?: string; content: string[] }> {
    const lines = content.split('\n');
    const sections: Array<{ title?: string; content: string[] }> = [];
    let currentSection: { title?: string; content: string[] } = { content: [] };

    for (const line of lines) {
      const trimmed = line.trim();

      if (trimmed.startsWith('# ')) {
        // New section with heading
        if (currentSection.title || currentSection.content.length > 0) {
          sections.push(currentSection);
        }
        currentSection = {
          title: trimmed.substring(2),
          content: [],
        };
      } else if (trimmed.startsWith('## ')) {
        // Subsection - also creates new slide
        if (currentSection.title || currentSection.content.length > 0) {
          sections.push(currentSection);
        }
        currentSection = {
          title: trimmed.substring(3),
          content: [],
        };
      } else if (trimmed !== '') {
        currentSection.content.push(trimmed);
      }
    }

    // Add the last section
    if (currentSection.title || currentSection.content.length > 0) {
      sections.push(currentSection);
    }

    return sections.length > 0 ? sections : [{ content: [content] }];
  }

  private formatContentForSlide(contentLines: string[]): PptxGenJS.TextProps[] {
    const formattedContent: PptxGenJS.TextProps[] = [];

    for (const line of contentLines) {
      if (line.startsWith('- ') || line.startsWith('* ')) {
        // Bullet point
        formattedContent.push({
          text: line.substring(2),
          options: { bullet: true },
        });
      } else {
        // Regular paragraph
        formattedContent.push({
          text: line,
          options: { paragraph: true },
        });
      }
    }

    return formattedContent;
  }

  private extractText(run: OSFTextRun): string {
    if (typeof run === 'string') return run;
    if (run.type === 'link') return run.text;
    if (run.type === 'image') return run.alt || '';
    if ('text' in run && typeof run.text === 'string') return run.text;
    return '';
  }

  private createChartSlide(pptx: PptxGenJS, chart: ChartBlock, options: ConverterOptions): void {
    void options;
    const slide = pptx.addSlide();

    slide.addText(chart.title, {
      x: 0.5,
      y: 0.5,
      w: 9,
      h: 0.75,
      fontSize: 32,
      bold: true,
      color: '2C3E50',
    });

    const chartData = chart.data.map((series: ChartDataSeries) => ({
      name: series.label,
      labels: series.values.map((_, i) => `Point ${i + 1}`),
      values: series.values,
    }));

    slide.addChart(pptx.ChartType[chart.chartType === 'bar' ? 'bar' : 'line'], chartData, {
      x: 1,
      y: 1.5,
      w: 8,
      h: 5,
      showTitle: false,
      showLegend: chart.options?.legend !== false,
      chartColors: chart.options?.colors || undefined,
    });
  }

  private createDiagramSlide(
    pptx: PptxGenJS,
    diagram: DiagramBlock,
    options: ConverterOptions
  ): void {
    void options;
    const slide = pptx.addSlide();

    const title = diagram.title || `${diagram.diagramType} Diagram`;
    slide.addText(title, {
      x: 0.5,
      y: 0.5,
      w: 9,
      h: 0.75,
      fontSize: 32,
      bold: true,
      color: '2C3E50',
    });

    slide.addText(`[${diagram.diagramType} diagram using ${diagram.engine}]`, {
      x: 1,
      y: 1.5,
      w: 8,
      h: 0.5,
      fontSize: 18,
      italic: true,
      color: '7F8C8D',
    });

    slide.addText(diagram.code, {
      x: 1,
      y: 2.5,
      w: 8,
      h: 4,
      fontSize: 14,
      fontFace: 'Courier New',
      color: '2C3E50',
      valign: 'top',
    });
  }

  private createCodeSlide(pptx: PptxGenJS, code: OSFCodeBlock, options: ConverterOptions): void {
    void options;
    const slide = pptx.addSlide();

    const title = code.caption || `${code.language} Code`;
    slide.addText(title, {
      x: 0.5,
      y: 0.5,
      w: 9,
      h: 0.75,
      fontSize: 32,
      bold: true,
      color: '2C3E50',
    });

    let codeText = code.code;
    if (code.lineNumbers) {
      const lines = code.code.split('\n');
      codeText = lines
        .map((line: string, i: number) => `${(i + 1).toString().padStart(3, ' ')}  ${line}`)
        .join('\n');
    }

    slide.addText(codeText, {
      x: 0.75,
      y: 1.5,
      w: 8.5,
      h: 5,
      fontSize: 14,
      fontFace: 'Courier New',
      color: '24292E',
      fill: { color: 'F6F8FA' },
      valign: 'top',
    });
  }

  private getMetadata(document: OSFDocument): { title?: string; author?: string; date?: string } {
    for (const block of document.blocks) {
      if (block.type === 'meta') {
        const meta = block as MetaBlock;
        return {
          title: meta.props.title ? String(meta.props.title) : undefined,
          author: meta.props.author ? String(meta.props.author) : undefined,
          date: meta.props.date ? String(meta.props.date) : undefined,
        };
      }
    }
    return {};
  }

  private getThemeConfiguration(theme: string): ThemeConfig {
    const themes: Record<string, ThemeConfig> = {
      default: {
        primary: '2C3E50',
        secondary: '7F8C8D',
        accent: '3498DB',
        text: '2C3E50',
        background: 'FFFFFF',
        border: 'DDDDDD',
        tableBackground: 'F8F9FA',
        titleFont: 'Calibri',
        bodyFont: 'Calibri',
      },
      corporate: {
        primary: '1A365D',
        secondary: '4A5568',
        accent: '2B6CB0',
        text: '2D3748',
        background: 'FFFFFF',
        border: '2B6CB0',
        tableBackground: 'EBF4FF',
        titleFont: 'Arial',
        bodyFont: 'Arial',
      },
      academic: {
        primary: '2D3748',
        secondary: '4A5568',
        accent: '4A5568',
        text: '1A202C',
        background: 'FFFFFF',
        border: '4A5568',
        tableBackground: 'F7FAFC',
        titleFont: 'Times New Roman',
        bodyFont: 'Times New Roman',
      },
      modern: {
        primary: '6366F1',
        secondary: '8B5CF6',
        accent: '06B6D4',
        text: '1F2937',
        background: 'FFFFFF',
        border: 'E5E7EB',
        tableBackground: 'F9FAFB',
        titleFont: 'Segoe UI',
        bodyFont: 'Segoe UI',
      },
      dark: {
        primary: 'F59E0B',
        secondary: 'FCD34D',
        accent: '10B981',
        text: 'E5E7EB',
        background: '1F2937',
        border: '4B5563',
        tableBackground: '374151',
        titleFont: 'Calibri',
        bodyFont: 'Calibri',
      },
      minimal: {
        primary: '000000',
        secondary: '666666',
        accent: '000000',
        text: '333333',
        background: 'FFFFFF',
        border: 'CCCCCC',
        tableBackground: 'FAFAFA',
        titleFont: 'Helvetica',
        bodyFont: 'Helvetica',
      },
      vibrant: {
        primary: 'EC4899',
        secondary: 'F472B6',
        accent: '8B5CF6',
        text: '1F2937',
        background: 'FFFFFF',
        border: 'E5E7EB',
        tableBackground: 'FDF4FF',
        titleFont: 'Arial',
        bodyFont: 'Arial',
      },
      ocean: {
        primary: '0EA5E9',
        secondary: '06B6D4',
        accent: '3B82F6',
        text: '0F172A',
        background: 'FFFFFF',
        border: 'BAE6FD',
        tableBackground: 'F0F9FF',
        titleFont: 'Calibri',
        bodyFont: 'Calibri',
      },
      forest: {
        primary: '059669',
        secondary: '10B981',
        accent: '14B8A6',
        text: '064E3B',
        background: 'FFFFFF',
        border: 'A7F3D0',
        tableBackground: 'F0FDF4',
        titleFont: 'Georgia',
        bodyFont: 'Georgia',
      },
      sunset: {
        primary: 'DC2626',
        secondary: 'F97316',
        accent: 'FBBF24',
        text: '7C2D12',
        background: 'FFFFFF',
        border: 'FED7AA',
        tableBackground: 'FFF7ED',
        titleFont: 'Arial',
        bodyFont: 'Arial',
      },
    };

    return themes[theme] || themes.default;
  }
}
